version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mycuisinedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
