version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - DATABASE_URL=mysql+pymysql://efrei:mlinprod@db/mycuisine_db
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mycuisine_db
      MYSQL_USER: efrei
      MYSQL_PASSWORD: mlinprod
      MYSQL_ROOT_PASSWORD: dummy
    ports:
      - "3306:3306"
    volumes:
      - mycuisine-db:/var/lib/mysql

volumes:
  mycuisine-db:
