#CD
name: Deploy MyCuisine Collection

on:
  push:
    branches:
      - main 
      - kadidia 

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t my-cuisine-collection:latest .
        docker tag my-cuisine-collection:latest kadidiac/my-cuisine-collection:latest
        docker push kadidiac/my-cuisine-collection:latest
